### ISSUE TITLE
How to get it running?

### ISSUE THREAD

**Issue by quintz** [tfeldmann/python-raumfeld#10]
Hi Thomas,

I stumbled upon your project because I wanted to make some automatization via pimatic (https://pimatic.org/)

Installed pyhton and the executed the 

`pip install raumfeld`

But then...yeah what then?
How do I proceed? Do I have to execute the setup.py? If yes, I cannot get it running...

Could you maybe give me a helping hand?

Thanks in advance.

quintz

**Comment by tilltnet** [comment]
Hey Quintz, you might want to check out [PyRaumfeld](https://github.com/maierp/PyRaumfeld) it supports almost all control functions of the Raumfeld system. It comes with a small WebServer that allows for easy automation via http requests. Just download it and start RaumfeldControl.py like this
`python2.7 /path/to/RaumfeldControl.py`

Sorry for hijacking this - python-raumfeld is a great library! - but I think it's not what quintz is looking for.

Best.

**Comment by quintz** [comment]
Even though it's an other lib, I still won't get yours running.
Everytime I execute it I get 

```
Traceback (most recent call last):
  File "/home/pi/raumfeld/PyRaumfeld-master/RaumfeldControl.py", line 12, in <module>
    from bottle import route, run
ImportError: No module named bottle
```

Thoughts? : /

**Comment by tilltnet** [comment]
`pip install bottle`
should do the trick for you. 
if you run in other problems you should open an issue over there
